const rewards = [
  {
    id: 1,
    title: "Discord VIP Role & Custom Badge",
    description: "Unlock an exclusive glowing VIP role on the official LOV Discord server and profile badge on the portal.",
    pointsCost: 500,
    category: "Digital Perks",
    stock: "Unlimited",
    featured: true,
    icon: "Crown",
  },
  {
    id: 2,
    title: "Discord Nitro (1 Month)",
    description: "Redeem your dubbing and editing contribution points for a full month of Discord Nitro.",
    pointsCost: 1200,
    category: "Subscriptions",
    stock: "5 Left",
    featured: true,
    icon: "Sparkles",
  },
  {
    id: 3,
    title: "Official LOV Jersey / T-Shirt",
    description: "Custom-printed Legion of Vocals anime edition jersey delivered to your doorstep in Bangladesh.",
    pointsCost: 2500,
    category: "Merchandise",
    stock: "12 Left",
    featured: true,
    icon: "Shirt",
  },
  {
    id: 4,
    title: "Studio Pop Filter & Mic Arm",
    description: "Upgrade your home recording booth with a broadcast-grade pop filter and adjustable boom arm.",
    pointsCost: 3500,
    category: "Recording Gear",
    stock: "3 Left",
    featured: false,
    icon: "Mic",
  },
  {
    id: 5,
    title: "Featured Cast Spotlight",
    description: "Get featured on the LOV homepage, YouTube community tab, and Facebook page for a week.",
    pointsCost: 800,
    category: "Community",
    stock: "Unlimited",
    featured: false,
    icon: "Star",
  },
  {
    id: 6,
    title: "USB Condenser Microphone",
    description: "Professional cardioid condenser mic for top-tier voice actors and dedicated community contributors.",
    pointsCost: 6000,
    category: "Recording Gear",
    stock: "2 Left",
    featured: true,
    icon: "Headphones",
  },
];

export default rewards;
